### ISSUE TITLE
Issue with creating new customer while adding appointment

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#184]
![firefox_6X5QIdhGyT](https://github.com/wpappointments/wpappointments/assets/66020772/0330de22-ee43-413f-b974-f528c5a39748)
After adding a new customer there is a toast indicating that the customer was created, but nothing else happens. After escaping the user edit screen there is still an option to add/search customers available and the screen breaks when trying to select one. 
The same happens when both - only required, or all - fields are filled.
Checked on Chrome and FF

**Comment by AniaSzlkwcz** [comment]
Additional info - The issue occurs only when checkbox "create account" is checked

**Comment by dawidurbanski** [comment]
Fixed
