### ISSUE TITLE
Day and Week views in Calendar view not working

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#185]
Changing the calendar view to Week or Day looks like it's available but is not doing anything. 
![firefox_C7vxJualrQ](https://github.com/wpappointments/wpappointments/assets/66020772/b601013d-7640-4632-b95e-5219bc7f58b1)
(Suggestion of greying them out if they are not available options yet)

**Comment by dawidurbanski** [comment]
This is not available yet as mentioned in the demo limitations section.

![CleanShot 2024-03-17 at 23 26 56@2x](https://github.com/wpappointments/wpappointments/assets/12466568/f403fe18-634d-456b-baef-62f3b6d8899a)

I think we should do some messaging here on click to indicate it's still WIP.

**Comment by dawidurbanski** [comment]
@marcinkrzeminski can you handle this on Monday? Let's do just a simple `alert('message')` for these two to let people know we are still working on the calendar view.
