### ISSUE TITLE
Wrong info while adding an appointment to a day with working hours set to "all day"

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#192]
When "all day" is selected as working hours, there is still information that selected time is outside of working hours:
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/b892f92d-75b8-496d-a7ba-a6086570c413)
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/ea83e951-f2ad-4861-83ea-9d8e5ce43cef)

**Comment by marcinkrzeminski** [comment]
@dawidurbanski fixed. Please review: https://github.com/wpappointments/wpappointments/pull/217
