### ISSUE TITLE
"Find time" view displays days with "all day" wroking hours as available even though they are turned off

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#194]
![firefox_VgbZxX0bAG](https://github.com/wpappointments/wpappointments/assets/66020772/0b026ae3-8c74-4a3c-9921-a032449d71ac)

**Comment by marcinkrzeminski** [comment]
@dawidurbanski fixed. Please review: https://github.com/wpappointments/wpappointments/pull/216
