### ISSUE TITLE
Issue with appointment status

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#197]
An appointment is added as "confirmed" even if another status was chosen during the creation 
![firefox_igBNCVs82U](https://github.com/wpappointments/wpappointments/assets/66020772/c34ae965-910a-40eb-9186-43523eed7a11)

**Comment by marcinkrzeminski** [comment]
@dawidurbanski please review: https://github.com/wpappointments/wpappointments/pull/212
