### ISSUE TITLE
Custom date and time not working

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#199]
When providing a custom date and/or time format, even the ones straight from [attached documentation](https://wordpress.org/documentation/article/customize-date-and-time-format/), there is an error and calendar view gets blank after trying to schedule an appointment 
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/1167566f-a429-49fb-844e-72063c11c2a6)
The same happens for the client on the frontend:
![firefox_xM7aeGyTPV](https://github.com/wpappointments/wpappointments/assets/66020772/64561ec1-9434-4d9f-901c-ef1c7443f96a)
Also, it would be nice if this was foolproof so that when a user provides clearly wrong format, they would get any kind of notice that this is not valid / can make schedules stop working.

**Comment by dawidurbanski** [comment]
Fix is for now to remove this setting at all
