### ISSUE TITLE
"Find time" calendar view sometimes don't display available slots

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#203]
Noticed a few times that sometimes after setting new working hours, when going into "Find time" view in new appointment edition, the available slots appear just for a blink and then disappear. They are still not there after opening the view again. They appear however after page refresh.
![uj67EOP4T4](https://github.com/wpappointments/wpappointments/assets/66020772/68438989-81a4-400b-b196-be2614eb41aa)

**Comment by marcinkrzeminski** [comment]
@dawidurbanski this has been fixed. Please review.
