### ISSUE TITLE
Fix slots alignment in front calendar view

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#204]
In the Booking Flow block, when choosing the alignment Centered, everything is centered as expected. When choosing alignment Left, everything including slots get aligned left. However, when choosing alignment Right, the slots are the only thing still aligned left 
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/cf281305-c98e-4a38-a8a0-85c8a7b4e746)
The error message again is aligned right
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/6eefd45a-45ca-4f0b-9196-ffb43fdd0e5d)
So everything looks like the slots should also get aligned right when this alignment is chosen.

**Comment by marcinkrzeminski** [comment]
@dawidurbanski please review: https://github.com/wpappointments/wpappointments/pull/214
