### ISSUE TITLE
Confusing tooltip info on slots in "Find time" view

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#205]
My slots are 100min. Why does it say 10:00-10:30? The next slot starts correctly at 11:40. Looks like tooltip always assumes it's a 30min slot no matter what it actually is.
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/5b6276ae-bacb-42f2-8a28-7bbb66a5f7e5)

**Comment by AniaSzlkwcz** [comment]
After further tests, this is clearly connected to [this issue](https://github.com/wpappointments/wpappointments/issues/207#issue-2195966599)

**Comment by marcinkrzeminski** [comment]
@AniaSzlkwcz can you please check with the latest version of the plugin? I can't reproduce it on my end.

**Comment by AniaSzlkwcz** [comment]
@marcinkrzeminski replied in the connected issue

**Comment by dawidurbanski** [comment]
This is related to https://github.com/wpappointments/wpappointments/issues/202 and should be fixed when it's done

**Comment by dawidurbanski** [comment]
Should be fixed
