### ISSUE TITLE
Appointment edition screen title

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#206]
When entering the edition of an existing appointment, the button text is different than it is on a creation view (it clearly says Update), but the title of the screen still says "Create New Appointment". Would expect f.e. "Edit Appointment" to avoid confusion.
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/291132c7-d221-45de-a6b3-f1f86ce9e298)

**Comment by dawidurbanski** [comment]
Should be already fixed in the newest version.
