### ISSUE TITLE
Default values do not work while creating appointment in admin

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#207]
These are the values set 
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/2fa08834-987f-4b7a-93ba-0c9b70d4a406)
When going to appointment creation in admin, I still see 30min, although tooltip says it should be at least 100.
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/cf4e5b73-21ae-45c2-912d-ba80aac3d2e8)
If I don't bother to check and create the appointment like that knowing that I have it set in plugin's settings, the appointment is added with a duration 30min.
If I only just click in the field and out, the value changes automatically for the expected 100.
![firefox_HlkPlhB3A0](https://github.com/wpappointments/wpappointments/assets/66020772/6781e667-3b2e-4962-b1e5-89e44f2d764d)

**Comment by marcinkrzeminski** [comment]
@AniaSzlkwcz can you please check again on your end with the latest version of the plugin? I can't reproduce it on my end.

**Comment by AniaSzlkwcz** [comment]
@marcinkrzeminski Unfortunately, I still get that each time I check. Refreshing does not help, it just goes back to default 30min again.

I'm checking now on 0.1.2 version from zip, on ff and chrome.

The steps to reproduce are:
1. Change default appointment length and time picker precision (f.e. 100min)
2. Go to the calendar view and start creating a new appointment
3. Click "Select time" and check the default duration

![chrome_B7v4dX0Vua](https://github.com/wpappointments/wpappointments/assets/66020772/e41d0675-278e-4d81-9907-718fbf987b09)

When I then go back to the settings, my values (here 100min) are still there, so it looks like they are saved but I still have 30min by default in the appointment creation screen. Also checked with other values and I got the same result.

**Comment by marcinkrzeminski** [comment]
@AniaSzlkwcz what's your browser (including version) and operating system. I'm testing on Arc (Chromium) and macOS and it's working as expected (except the issue with time slots in Find Time which is already reported)

**Comment by AniaSzlkwcz** [comment]
@marcinkrzeminski I'm using Windows 11 with Polish, browsers: Firefox Developer 125.0b7 and Chrome 123.0.6312.105

However, when I test the same thing as on your video, I don't get the issue either. I only get the issue when trying to add an appointment using a button on the Calendar view, somehow the one from the Appointments view works as expected.
