### ISSUE TITLE
False warning when trying to set up a double appointment (taking up 2 slots)

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#209]
Both slots are available separately, yet when trying to set an appointment for 2 of them at once, there is a warning about not available hours
![firefox_Nb7ZitmMYH](https://github.com/wpappointments/wpappointments/assets/66020772/76116bf3-ebb2-41b5-b0e4-a6887310df00)

**Comment by dawidurbanski** [comment]
This should be fixed by: https://github.com/wpappointments/wpappointments/pull/231
