### ISSUE TITLE
Uncaught error when trying to add Booking Flow block

### ISSUE THREAD

**Issue by marcinkrzeminski** [wpappointments/wpappointments#213]
https://github.com/wpappointments/wpappointments/assets/2551613/63964447-e950-4564-8c90-7465380f2ef7

Steps to reproduce:
1. Go to one of the pages
2. Select all blocks in the list view
3. Hit `del` or `backspaceo` n keyboard to remove all of them

---
Got the same error when inserting the block and trying to save the page.

https://github.com/wpappointments/wpappointments/assets/2551613/fb1e5cd5-0916-4771-bf96-e0bd8e5e6dd8

**Comment by dawidurbanski** [comment]
Seems like this is fixed
