### ISSUE TITLE
Appointement edition screen lost appointment data

### ISSUE THREAD

**Issue by AniaSzlkwcz** [wpappointments/wpappointments#218]
After a change to a [edit screen title](https://github.com/wpappointments/wpappointments/issues/206#issue-2195937169) I can see "Edit Appointment" title, but the appointment details has vanished 
![obraz](https://github.com/wpappointments/wpappointments/assets/66020772/7d1d51f8-8ea5-4f02-a24b-e475181a3c4d)

**Comment by dawidurbanski** [comment]
Fixed
